In [2]:
import pickle 
import pandas as pd
from sklearn.preprocessing import MinMaxScaler ,LabelEncoder

In [3]:
with open("model_svm.pkl", "rb") as f:
    model = pickle.load(f)

c:\Users\Mohamed Essam\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:348: InconsistentVersionWarning: Trying to unpickle estimator SVC from version 1.4.0 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [4]:
test_df = pd.read_csv('../data/raw/test - test.csv')
test_df.head()

,id,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,1,1043,1,1.8,1,14,0,5,0.1,193,...,16,226,1412,3476,12,7,2,0,1,0
1,2,841,1,0.5,1,4,1,61,0.8,191,...,12,746,857,3895,6,0,7,1,0,0
2,3,1807,1,2.8,0,1,0,27,0.9,186,...,4,1270,1366,2396,17,10,10,0,1,1
3,4,1546,0,0.5,1,18,1,25,0.5,96,...,20,295,1752,3893,10,0,7,1,1,0
4,5,1434,0,1.4,0,11,1,49,0.5,108,...,18,749,810,1773,15,8,7,1,0,1

In [5]:
test_df.columns

Index(['id', 'battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc',
       'four_g', 'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc',
       'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi'],
      dtype='object')

In [8]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1000 non-null   int64
 1   battery_power  1000 non-null   int64
 2   blue           1000 non-null   int64
 3   clock_speed    1000 non-null   float64
 4   dual_sim       1000 non-null   int64
 5   fc             1000 non-null   int64
 6   four_g         1000 non-null   int64
 7   int_memory     1000 non-null   int64
 8   m_dep          1000 non-null   float64
 9   mobile_wt      1000 non-null   int64
 10  n_cores        1000 non-null   int64
 11  pc             1000 non-null   int64
 12  px_height      1000 non-null   int64
 13  px_width       1000 non-null   int64
 14  ram            1000 non-null   int64
 15  sc_h           1000 non-null   int64
 16  sc_w           1000 non-null   int64
 17  talk_time      1000 non-null   int64
 18  three_g        1000 non-null   int64
 19  touch_screen   1000 non-null   int64
 20  wifi           1000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 164.2 KB

In [9]:
test_df.isnull().sum()

id               0
battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
dtype: int64

In [13]:
test_df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,1000.0,500.5000,288.819436,1.0,250.75,500.5,750.25,1000.0
battery_power,1000.0,1248.5100,432.458227,500.0,895.00,1246.5,1629.25,1999.0
blue,1000.0,0.5160,0.499994,0.0,0.00,1.0,1.00,1.0
clock_speed,1000.0,1.5409,0.829268,0.5,0.70,1.5,2.30,3.0
dual_sim,1000.0,0.5170,0.499961,0.0,0.00,1.0,1.00,1.0
fc,1000.0,4.5930,4.463325,0.0,1.00,3.0,7.00,19.0
four_g,1000.0,0.4870,0.500081,0.0,0.00,0.0,1.00,1.0
int_memory,1000.0,33.6520,18.128694,2.0,18.00,34.5,49.00,64.0
m_dep,1000.0,0.5175,0.280861,0.1,0.30,0.5,0.80,1.0
mobile_wt,1000.0,139.5110,34.851550,80.0,109.75,139.0,170.00,200.0
n_cores,1000.0,4.3280,2.288155,1.0,2.00,4.0,6.00,8.0
pc,1000.0,10.0540,6.095099,0.0,5.00,10.0,16.00,20.0
px_height,1000.0,627.1210,432.929699,0.0,263.75,564.5,903.00,1907.0
px_width,1000.0,1239.7740,439.670981,501.0,831.75,1250.0,1637.75,1998.0
ram,1000.0,2138.9980,1088.092278,263.0,1237.25,2153.5,3065.50,3989.0
sc_h,1000.0,11.9950,4.320607,5.0,8.00,12.0,16.00,19.0
sc_w,1000.0,5.3160,4.240062,0.0,2.00,5.0,8.00,18.0
talk_time,1000.0,11.0850,5.497636,2.0,6.75,11.0,16.00,20.0
three_g,1000.0,0.7560,0.429708,0.0,1.00,1.0,1.00,1.0
touch_screen,1000.0,0.5000,0.500250,0.0,0.00,0.5,1.00,1.0
wifi,1000.0,0.5070,0.500201,0.0,0.00,1.0,1.00,1.0

In [15]:
test_df.head()

,id,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,1,1043,1,1.8,1,14,0,5,0.1,193,...,16,226,1412,3476,12,7,2,0,1,0
1,2,841,1,0.5,1,4,1,61,0.8,191,...,12,746,857,3895,6,0,7,1,0,0
2,3,1807,1,2.8,0,1,0,27,0.9,186,...,4,1270,1366,2396,17,10,10,0,1,1
3,4,1546,0,0.5,1,18,1,25,0.5,96,...,20,295,1752,3893,10,0,7,1,1,0
4,5,1434,0,1.4,0,11,1,49,0.5,108,...,18,749,810,1773,15,8,7,1,0,1

### `First we will normalize the data`

In [19]:
# Construct an instance of MinMaxScaler
scaler = MinMaxScaler(feature_range=(1, 5))
# Normalization of selected columns
df2 = test_df[['battery_power', 'clock_speed', 'fc', 'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time']]
df2_normalized = pd.DataFrame(scaler.fit_transform(df2), columns=df2.columns)

# Merge normalized columns with original columns from df1
df_norm= pd.concat([df2_normalized, test_df[['blue','dual_sim', 'four_g', 'three_g', 'touch_screen', 'wifi']]], axis=1)

df_norm
y_test_preds = model.predict(df_norm)

,battery_power,clock_speed,fc,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,blue,dual_sim,four_g,three_g,touch_screen,wifi
0,2.448966,3.08,3.947368,1.193548,1.000000,4.766667,2.142857,4.2,1.474043,3.434202,4.449275,3.000000,2.555556,1.000000,1,1,0,0,1,0
1,1.909940,1.00,1.842105,4.806452,4.111111,4.700000,3.285714,3.4,2.564761,1.951236,4.899087,1.285714,1.000000,2.111111,1,1,1,1,0,0
2,4.487658,4.68,1.210526,2.612903,4.555556,4.533333,2.142857,1.8,3.663870,3.311289,3.289855,4.428571,3.222222,2.777778,1,0,0,0,1,1
3,3.791194,1.00,4.789474,2.483871,2.777778,1.533333,5.000000,5.0,1.618773,4.342685,4.896940,2.428571,1.000000,2.111111,0,1,1,1,1,0
4,3.492328,2.44,3.315789,4.032258,2.777778,1.933333,3.857143,4.6,2.571054,1.825651,2.621041,3.857143,2.777778,2.111111,0,0,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,4.202135,3.24,1.000000,4.354839,2.777778,4.000000,4.428571,4.4,2.350813,2.100868,2.994632,3.571429,2.777778,3.888889,1,0,1,1,1,0
996,1.290861,3.08,1.000000,1.709677,4.555556,4.533333,2.714286,1.4,3.416361,4.022044,2.792807,1.857143,1.222222,4.777778,0,1,0,0,1,1
997,2.827885,2.44,1.210526,1.387097,2.777778,1.000000,1.000000,3.4,2.000524,1.865731,2.030596,1.000000,1.000000,3.666667,0,0,1,1,0,0
998,3.756504,1.00,1.000000,4.096774,2.333333,4.033333,1.571429,3.4,1.079706,1.884436,3.411165,3.857143,3.444444,1.888889,1,1,0,0,1,0
999,3.054703,1.00,1.842105,3.129032,1.000000,3.000000,3.857143,4.8,1.958574,1.285905,3.753623,2.142857,1.444444,1.222222,1,0,1,1,0,1

In [20]:
y_test_preds = model.predict(df_norm)

c:\Users\Aanaconda\envs\new\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(

In [21]:
test_df["price_range"] = y_test_preds

In [22]:
test_df.head()

,id,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,1,1043,1,1.8,1,14,0,5,0.1,193,...,226,1412,3476,12,7,2,0,1,0,3
1,2,841,1,0.5,1,4,1,61,0.8,191,...,746,857,3895,6,0,7,1,0,0,3
2,3,1807,1,2.8,0,1,0,27,0.9,186,...,1270,1366,2396,17,10,10,0,1,1,2
3,4,1546,0,0.5,1,18,1,25,0.5,96,...,295,1752,3893,10,0,7,1,1,0,3
4,5,1434,0,1.4,0,11,1,49,0.5,108,...,749,810,1773,15,8,7,1,0,1,1

In [23]:
test_df.to_csv("../data/processed/predicted_data.csv",index=False)